language: cpp
env:
  - QT_SELECT=qt4
  - QT_SELECT=qt5
install:
  - tests/travis/install-build-depends
before_script:
  - mysql -e 'create database qdjango_test'
  - psql -c 'create database qdjango_test' -U postgres
script:
  - tests/travis/build-and-test
