language: cpp
env:
  - QT_SELECT=qt4 QDJANGO_DB_DRIVER=QSQLITE
  - QT_SELECT=qt4 QDJANGO_DB_DRIVER=QMYSQL QDJANGO_DB_NAME=qdjango_test QDJANGO_DB_USER=travis
  - QT_SELECT=qt4 QDJANGO_DB_DRIVER=QPSQL QDJANGO_DB_NAME=qdjango_test QDJANGO_DB_USER=postgres
  - QT_SELECT=qt5 QDJANGO_DB_DRIVER=QSQLITE
  - QT_SELECT=qt5 QDJANGO_DB_DRIVER=QMYSQL QDJANGO_DB_NAME=qdjango_test QDJANGO_DB_USER=travis
  - QT_SELECT=qt5 QDJANGO_DB_DRIVER=QPSQL QDJANGO_DB_NAME=qdjango_test QDJANGO_DB_USER=postgres
install:
  - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get -qq update
  - sudo apt-get -qq install libqt4-dev libqt4-sql-mysql libqt4-sql-psql libqt4-sql-sqlite qtbase5-dev qtscript5-dev
before_script:
  - mysql -e 'create database qdjango_test'
  - psql -c 'create database qdjango_test' -U postgres
script:
  - qmake
  - make
  - tests/run.py
