language: cpp
env:
  - QT_SELECT=qt4
  - QT_SELECT=qt5
install:
  - tests/install-build-depends
before_script:
  - mysql -e 'create database qdjango_test'
  - psql -c 'create database qdjango_test' -U postgres
script:
  - qmake
  - make
  - QDJANGO_DB_DRIVER=QSQLITE tests/run.py
  - QDJANGO_DB_DRIVER=QMYSQL QDJANGO_DB_NAME=qdjango_test QDJANGO_DB_USER=travis tests/run.py
  - QDJANGO_DB_DRIVER=QPSQL QDJANGO_DB_NAME=qdjango_test QDJANGO_DB_USER=postgres tests/run.py
